name: Yoroshiku Fantastic K.K.
favicon: null
layout_spectrum: 0.9864239459857345
typography_spectrum: 0.044301215559244156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7006870482582599
  lightness: 0.6036646571010351
  saturation: 0.7457910052035004
  rhythmicContrast: 0.96292455191724
purpose: []
