title: YF
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#684192'
    - '#FFD203'
    - '#997E00'
    - '#A38664'
    - '#D0A4BC'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Yoroshiku Fantastic K.K.
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5107527
layout_spectrum: 1
